debug: true
# Default language
default-language: en
# Disable all metrics included in this plugin.
disable-metrics: false
# Whether or not resourcepack file hashes should be generated on startup:
autogeneratehashes: true
# Whether /usepack should apply packs temporary or permanent when run without any argument:
usepack-is-temporary: true
# Whether packs that a player has stored will override a matched assignments
stored-packs-override-assignments: false
# When manually setting a permanent pack then it will be reset if the user disconnects in under x amount of seconds.
# 0 or anything below will disable this functionality
permanent-pack-remove-time: 30
# Whether to only send packs if authenticated on the Minecraft server
# Requires WorldResourcepacks to be installed on the Minecraft server too
use-auth-plugin: false
packs:
  lobbypack: 
   # The url the client should download the resourcepack from.
   # Has to be a direct download link! No mediafire/mega/other oneclick-hoster!
    url: http://example.com/lobbyresourcepack.zip
   # The sha1 hash of the resourcepack's zip file, 
   # if not correct the client will waste bandwidth but it will still work!
   # At least that's what the Minecraft wiki says... (Site: Server.properties#Minecraft_server_properties)
    hash: abcdef012345678abcdef012345678abcdef0123
   # The format version of this resourcepack
    format: 1
   # Directly define the Minecraft version instead of the format
   # Supports string representation of the versions and protocol numbers
   # You don't need to define both the version and the format (if so then the highest one will take effect)
    version: "1.8"
   # Whether or not this pack will only be send to players with a certain permission
   # permission: velocityresourcepacks.pack.<packname>
    restricted: false
   # If you want you can define a specific permission for this pack if you don't want
   # the default velocityresourcepacks.pack.<packname> permission!
    permission: velocityresourcepacks.pack.lobbypack
  globalpack:
    url: http://example.com/globalpack.zip
    hash: abcdef012345678abcdef012345678abcdef0123
  gamepack:
    # Set different variants e.g. for different versions or permissions
    # This list supports all normal pack settings and is checked top to bottom.
    # The first one that matches the player will be used.
    variants:
    - url: http://example.com/minigameresourcepack_1_15.zip
      hash: 012345678abcdef012345678abcdef012345678a
      version: '1.15'
    - url: http://example.com/minigameresourcepack_1_12.zip
      hash: 012345678abcdef01234567dddcdef012345678a
      version: '1.12'
# Empty pack to reset the pack to the default one
empty:
  url: http://cdn.moep.tv/files/Empty.zip
  hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
global:
  # Define a global pack:
  pack: globalpack
  # List of packs to not replace if the user already has them
  # If no main pack is set the first one also gets used to reset 
  # the pack if the user has a non secondary one
  # Also this list will be used to select a pack if a user does not have the permission
  # or the right version to use that pack. (From top to bottom)
  secondary:
  - lobbypack
  # Delay in ticks before sending the pack to a player after he logs in/switches to the server
  send-delay: 20
servers:
  lobby:
    pack: lobbypack
    secondary:
    - gamepack
  minigame:
    pack: gamepack
    # Use a regex to target all servers with a certain name
    regex: 'minigame_.*'